name: Profile README Stats

on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  push:
    branches:
      - master
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v3
      with:
        token: ${{ secrets.USER_TOKEN }}
        template: ./TEMPLATE.md
        readme: ./README.md
        includeForks: false

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
          git add README.md
          git commit -m "Update README"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:$(git rev-parse --abbrev-ref HEAD)
        fi
